#!/bin/sh

# Check for changed files
CHANGED_FILES=$(git diff --cached --name-only)

if echo "$CHANGED_FILES" | grep -q "^frontend/"; then
  echo "Running lint-staged for frontend..."
  (cd frontend && npm run lint-staged)
fi

if echo "$CHANGED_FILES" | grep -q "^backend/"; then
  echo "Running lint-staged for backend..."
  (cd backend && npm run lint-staged)
fi
